
language: php

php:
    - 7.0
    - 7.4

before_script:
    - composer install -no

script:
    - php ./vendor/bin/phpunit

after_success:
    - curl -s https://codecov.io/bash | bash

notifications:
    email:
        on_success: never
        on_failure: always

